spring.datasource.url=${RENDER_POSTGRES_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# 改回標準 Dialect 並加上關鍵禁令
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# 關鍵建表與初始化設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# 第三方服務與變數映射 (保持不變)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
Mapbox.token=${MAPBOX_TOKEN}
Gmail.password=${GMAIL_PASSWORD}
GMAIL_USERNAME=${GMAIL_USERNAME}
JWT_SECRET=${JWT_SECRET}

app.seeder.enabled=true

# 系統與日誌
spring.main.banner-mode=off
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG